name: dbanonymizer
config:
  composer_version: 2
services:
  appserver:
    type: php:8.2
    xdebug: true
tooling:
  console:
    service: appserver
    cmd: php /app/bin/console
    description: 'Runs symfony console commands'
  php:
    service: appserver
    cmd: php
  composer:
    service: appserver
  test:
    service: appserver
    cmd: composer test
    description: 'Run phpunit'
  psalm:
    service: appserver
    cmd: composer psalm
    description: 'Run phpunit'
  phpdebug:
    service: appserver
    cmd: php
    env:
      XDEBUG_TRIGGER: 1
      PHP_IDE_CONFIG: "serverName=localhost"
