name: dbanonymizer
config:
  composer_version: 2
services:
  appserver:
    type: php:8.2
    xdebug: true
    build_as_root:
      - apt update
      - apt install nano mc -y
    build:
      - composer global require escapestudios/symfony2-coding-standard
      - $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/escapestudios/symfony2-coding-standard
      - echo 'export PATH="$PATH:$HOME/.config/composer/vendor/bin"' >> ~/.profile
      - sh .gitlab/_scripts/init-hooks.sh
tooling:
  phpcs:branch:
    service: appserver
    cmd: git diff --diff-filter=d develop --name-only -- '*.php' | xargs -r /app/vendor/bin/phpcs --standard=/app/phpcs.xml --colors
    description: Runs phpcbf command to fix files updated on current git branch.
  phpcbf:branch:
    service: appserver
    cmd: git diff --diff-filter=d develop --name-only -- '*.php' | xargs -r /app/vendor/bin/phpcbf --standard=/app/phpcs.xml
    description: Runs phpcbf command to fix files updated on current git branch.
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --standard=/app/phpcs.xml --colors
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=/app/phpcs.xml
  console:
    service: appserver
    cmd: php /app/bin/console
    description: 'Runs symfony console commands'
  php:
    service: appserver
    cmd: php
  composer:
    service: appserver
  test:
    service: appserver
    cmd: composer test
    description: 'Run phpunit'
  phpdebug:
    service: appserver
    cmd: php
    env:
      XDEBUG_TRIGGER: 1
      PHP_IDE_CONFIG: "serverName=localhost"
