version: "3.2"

services:
  php-cli:
    build:
      context: ./docker
      dockerfile: ./dev/php-cli.dockerfile
    environment:
      APP_DEBUG: 1
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - ${HOME}/.composer:/.composer

volumes:
  composer:
