#!/usr/bin/env sh

echo "Executing .git/hooks/pre-push..."
git diff --diff-filter=d  origin/$(git rev-parse --abbrev-ref HEAD) --name-only -- '*.php' | xargs -r phpcs --standard=phpcs.xml --colors

# Return the status of the last run command.
exit $?
