parameters:
    database_dump_folder: '%env(DATABASE_DUMP_FOLDER)%'
    pg_dump: '%env(PG_DUMP)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Service\DDL\Extractor\DbDriverNameInterface:
            tags: [ 'app.dbStructureExtractor' ]
        App\Service\DDL\Extractor\DbStructureExtractorInterface:
            bind:
                $pgDump: '%pg_dump%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\DDL\ExtractorFactory:
        arguments:
            $extractors: !tagged_iterator app.dbStructureExtractor

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Doctrine\DBAL\Tools\DsnParser:
